#!/usr/bin/env python3
"""
📁 Sample 06: File Upload và Download Operations
Demo các thao tác với file theo README
"""

import os
import tempfile
from pathlib import Path
from nova_act import NovaAct

def create_test_file():
    """Tạo file test để upload"""
    test_content = """# Test File for Nova Act Demo

This is a test file created for demonstrating file upload functionality.

## Content
- Line 1: Hello World
- Line 2: Nova Act Demo
- Line 3: File Upload Test

Generated by Nova Act Sample 06
"""
    
    # Tạo file tạm
    with tempfile.NamedTemporaryFile(mode='w', suffix='.txt', delete=False) as f:
        f.write(test_content)
        return f.name

def demo_file_upload():
    """Demo upload file"""
    
    print("📤 Demo File Upload")
    print("-" * 30)
    
    # Tạo file test
    upload_file = create_test_file()
    print(f"📄 Tạo file test: {upload_file}")
    
    try:
        with NovaAct(
            starting_page="https://file.io",  # Free file upload service
            headless=False
        ) as nova:
            
            print("🔍 Tìm file upload input...")
            nova.act("find the file upload area or input")
            
            # Sử dụng Playwright để upload file
            print(f"📤 Đang upload file: {Path(upload_file).name}")
            nova.page.set_input_files('input[type="file"]', upload_file)
            
            # Chờ upload hoàn thành
            print("⏳ Chờ upload hoàn thành...")
            nova.act("wait for the upload to complete")
            
            # Lấy link download nếu có
            nova.act("get the download link if available")
            
            print("✅ Upload hoàn thành!")
            
    except Exception as e:
        print(f"❌ Lỗi upload: {e}")
    finally:
        # Xóa file test
        if os.path.exists(upload_file):
            os.unlink(upload_file)
            print(f"🗑️ Đã xóa file test: {upload_file}")

def demo_file_download_button():
    """Demo download file qua button"""
    
    print("\n📥 Demo File Download (Button)")
    print("-" * 30)
    
    try:
        with NovaAct(
            starting_page="https://sample-files.com/zip/10/mp3/SampleAudio_0.4mb_mp3.zip",
            headless=False
        ) as nova:
            
            print("🔍 Tìm download button...")
            
            # Sử dụng Playwright để capture download
            with nova.page.expect_download() as download_info:
                nova.act("click on the download button")
            
            # Lấy thông tin download
            download = download_info.value
            temp_path = download.path()
            
            print(f"📥 File đã download: {temp_path}")
            print(f"📊 Kích thước: {os.path.getsize(temp_path)} bytes")
            
            # Lưu file vào vị trí mong muốn
            save_path = "downloaded_sample.zip"
            download.save_as(save_path)
            
            print(f"💾 Đã lưu file: {save_path}")
            
            # Xóa file sau demo
            if os.path.exists(save_path):
                os.unlink(save_path)
                print(f"🗑️ Đã xóa file demo: {save_path}")
            
    except Exception as e:
        print(f"❌ Lỗi download: {e}")

def demo_page_content_download():
    """Demo download nội dung trang hiện tại"""
    
    print("\n📄 Demo Download Page Content")
    print("-" * 30)
    
    try:
        with NovaAct(
            starting_page="https://httpbin.org/json",  # API trả về JSON
            headless=True
        ) as nova:
            
            print("📖 Đang lấy nội dung trang...")
            
            # Lấy HTML content
            html_content = nova.page.content()
            print(f"📝 HTML content length: {len(html_content)} chars")
            
            # Lưu HTML
            with open("page_content.html", "w", encoding="utf-8") as f:
                f.write(html_content)
            print("💾 Đã lưu HTML content")
            
            # Nếu là PDF hoặc file khác, dùng request
            print("📥 Đang download content qua request...")
            response = nova.page.request.get(nova.page.url)
            
            with open("api_response.json", "wb") as f:
                f.write(response.body())
            
            print("💾 Đã lưu API response")
            
            # Xóa files demo
            for file in ["page_content.html", "api_response.json"]:
                if os.path.exists(file):
                    os.unlink(file)
                    print(f"🗑️ Đã xóa: {file}")
            
    except Exception as e:
        print(f"❌ Lỗi: {e}")

def demo_multiple_file_upload():
    """Demo upload nhiều file"""
    
    print("\n📤 Demo Multiple File Upload")
    print("-" * 30)
    
    # Tạo nhiều file test
    test_files = []
    for i in range(3):
        content = f"Test file {i+1}\nContent for file number {i+1}"
        with tempfile.NamedTemporaryFile(mode='w', suffix=f'_test_{i+1}.txt', delete=False) as f:
            f.write(content)
            test_files.append(f.name)
    
    print(f"📄 Tạo {len(test_files)} file test")
    
    try:
        with NovaAct(
            starting_page="https://file.io",
            headless=False
        ) as nova:
            
            print("🔍 Tìm multiple file upload...")
            nova.act("find file upload input that supports multiple files")
            
            # Upload tất cả files
            print(f"📤 Đang upload {len(test_files)} files...")
            nova.page.set_input_files('input[type="file"]', test_files)
            
            # Chờ upload
            nova.act("wait for all uploads to complete")
            
            print("✅ Multiple upload hoàn thành!")
            
    except Exception as e:
        print(f"❌ Lỗi multiple upload: {e}")
    finally:
        # Xóa test files
        for file in test_files:
            if os.path.exists(file):
                os.unlink(file)
        print(f"🗑️ Đã xóa {len(test_files)} file test")

def demo_drag_drop_upload():
    """Demo drag & drop upload"""
    
    print("\n🖱️ Demo Drag & Drop Upload")
    print("-" * 30)
    
    upload_file = create_test_file()
    
    try:
        with NovaAct(
            starting_page="https://file.io",
            headless=False
        ) as nova:
            
            print("🎯 Tìm drag & drop area...")
            nova.act("find the drag and drop upload area")
            
            # Simulate drag & drop bằng cách set file input
            print("🖱️ Simulate drag & drop...")
            nova.page.set_input_files('input[type="file"]', upload_file)
            
            nova.act("wait for drag and drop upload to complete")
            
            print("✅ Drag & drop upload hoàn thành!")
            
    except Exception as e:
        print(f"❌ Lỗi drag & drop: {e}")
    finally:
        if os.path.exists(upload_file):
            os.unlink(upload_file)

def main():
    """Demo file operations"""
    
    # Kiểm tra API key
    api_key = os.getenv('NOVA_ACT_API_KEY')
    if not api_key:
        print("❌ Vui lòng set NOVA_ACT_API_KEY")
        return
    
    print("📁 Sample 06: File Upload & Download Operations")
    print("=" * 50)
    print("📤📥 Demo các thao tác với file")
    
    # Danh sách demos
    demos = [
        ("File Upload", demo_file_upload),
        ("File Download (Button)", demo_file_download_button),
        ("Page Content Download", demo_page_content_download),
        ("Multiple File Upload", demo_multiple_file_upload),
        ("Drag & Drop Upload", demo_drag_drop_upload)
    ]
    
    print(f"\n📋 Sẽ chạy {len(demos)} demo:")
    for i, (name, _) in enumerate(demos, 1):
        print(f"   {i}. {name}")
    
    # Chạy từng demo
    for demo_name, demo_func in demos:
        print(f"\n{'='*50}")
        print(f"🎯 {demo_name}")
        print(f"{'='*50}")
        
        try:
            demo_func()
        except KeyboardInterrupt:
            print("⏸️ Demo bị dừng bởi user")
            break
        except Exception as e:
            print(f"❌ Lỗi trong {demo_name}: {e}")
        
        print(f"✅ Hoàn thành {demo_name}")
    
    print(f"\n💡 Ví dụ này minh họa:")
    print("   • nova.page.set_input_files() cho file upload")
    print("   • nova.page.expect_download() cho download capture")
    print("   • download.save_as() để lưu file")
    print("   • nova.page.content() cho HTML content")
    print("   • nova.page.request.get() cho binary content")
    print("   • Multiple file upload")
    print("   • Drag & drop simulation")
    
    print(f"\n📁 File Operations Checklist:")
    print("   ✅ Upload single file")
    print("   ✅ Upload multiple files")
    print("   ✅ Download via button click")
    print("   ✅ Download page content")
    print("   ✅ Handle different file types")
    print("   ✅ Drag & drop upload")

if __name__ == "__main__":
    main()
